// c1 = nova Caneta         // c1 = nome do objeto
			                // nova = instanciamento do objeto 
			                        //	(geração de objeto a partir de uma classe
			                // Caneta = classe
			                


// c1.Cor = azul            // c1 = nome do objeto
                            // c1.Cor = nome do atributo (variável)
                            // azul = Valor do atributo.
